name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: node:16-buster
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can
          # generate changelogs with the correct commits.
          fetch-depth: 0
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Changesets
        uses: changesets/action@21240c3cd1d2efa2672d64e0235a03cf139b83e6
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          publish: npx changeset publish
