name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: node:16-buster
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can
          # generate changelogs with the correct commits.
          fetch-depth: 0
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Changesets
        uses: changesets/action@37c2edd85bf5f2aa8edb44ce4ea00eb4a55aa9d4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          publish: npx changeset publish
